@startuml

title Todo Project Diagram 

object User {
    String username,
    String password,
    String avatarUrl,
    Array<Project> activeProjects
}
object Project {
    String title,
    Date createdAt,
    Date dueDate,
    Array<Todos> activeTodos

}
object Todos {
    int id,
    String title,
    String body,
    User assignedUser,
    String status
}

User -- Project
Project -- Todos

@enduml